In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib import cm

import keras

from keras.models import Sequential
from keras.layers import Dense

from sklearn.preprocessing import StandardScaler, LabelBinarizer
from sklearn.utils import shuffle
from sklearn.datasets import load_iris

ModuleNotFoundError: No module named 'tensorflow'

In [ ]:
df= pd.read_csv("iris.csv")

In [ ]:
df.head()

In [ ]:
data = pd.DataFrame(data= np.c_[data['data'], data['target']],
                     columns= data['feature_names'] + ['target'])

data

In [18]:
a = np.array(df.iloc[0])
a

array([5.1, 3.5, 1.4, 0.2, 'Setosa'], dtype=object)

In [5]:
X = df.iloc[:,:-1]
Y =df.iloc[:,4]


In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state=0)

In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
scaler = StandardScaler()

In [9]:
scaler.fit(X_train)

StandardScaler()

In [10]:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [11]:
from sklearn.neighbors import KNeighborsClassifier
cl = KNeighborsClassifier(n_neighbors=5)
cl.fit(X_train,Y_train)

KNeighborsClassifier()

In [12]:
Y_predict = cl.predict(X_test)

In [13]:
from sklearn.metrics import classification_report,confusion_matrix

In [14]:
print(classification_report(Y_test,Y_predict))
print(confusion_matrix(Y_test,Y_predict))

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        11
  Versicolor       1.00      1.00      1.00        13
   Virginica       1.00      1.00      1.00         6

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]


In [37]:
cl.predict([[7.1, 9.5, 1.4, 0.2]])

array(['Virginica'], dtype=object)